### ISSUE TITLE
[BUG] Chests don't spawn

### ISSUE THREAD

**Issue by materialplane** [promcteam/enigma#3]
When the server starts up the following file gets created, but no chests get queued up to spawn in the world.

<pre>
autoSaveTime: 18000
asyncSaveOnFind: true
commands:
- ==: RC_ItemCommand
  delay: 0
  as: CONSOLE
  cmd: say {player} found chest!
fireworks:
- ==: me.travja.darkrise.core.legacy.util.item.FireworkBuilder
  TYPE: firework
  power: 2
  effects:
  - type: BALL
    trail: false
    flicker: true
    colors:
    - ffff
    fadeColors: []
enabledWorlds:
- alleria
worlds:
  alleria:
    ==: RC_WorldChests
    world: alleria
    maxChests: 10
    minPoint:
      ==: RC_MapLocation
      x: -10
      z: -10
    maxPoint:
      ==: RC_MapLocation
      x: 10
      z: 10
    blockType: ENDER_CHEST:2
    chests: []
    chestsToSpawn: {}
</pre>

**Comment by Travja** [comment]
Pre 1.13? Grass blocks were called GRASS. After that, they are called GRASS_BLOCK and that change had yet to be reflected here. Chests should now spawn on grass or stone blocks in the given range.
